# Generated by Django 5.2.13 on 2026-05-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='kids',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='men',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='women',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
