# Generated by Django 5.2.14 on 2026-05-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_alter_accessory_size_alter_kids_size_alter_men_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('accessory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.accessory')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boutique.cart')),
                ('kid_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.kids')),
                ('man_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.men')),
                ('woman_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.women')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.accessory')),
                ('kid_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.kids')),
                ('man_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.men')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('woman_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.women')),
            ],
        ),
    ]
