# Generated by Django 5.2.14 on 2026-05-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_cart_cartitem_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('jewelry', 'Jewelry'), ('handbags', 'Handbags'), ('scarves', 'Scarves')], default='jewelry', max_length=20),
        ),
        migrations.AlterField(
            model_name='kids',
            name='category',
            field=models.CharField(choices=[('kidswear', 'Kids Wear'), ('toys', 'Toys'), ('footwear', 'Footwear')], default='kidswear', max_length=20),
        ),
        migrations.AlterField(
            model_name='men',
            name='category',
            field=models.CharField(choices=[('kurta', 'Kurta'), ('sherwani', 'Sherwani'), ('waistcoat', 'Waistcoat')], default='kurta', max_length=20),
        ),
    ]
