# Generated by Django 5.2.14 on 2026-05-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_accessory_category_alter_kids_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='details',
            field=models.TextField(blank=True, help_text='Enter material, design, pattern, and care instructions.', null=True),
        ),
        migrations.AddField(
            model_name='kids',
            name='details',
            field=models.TextField(blank=True, help_text='Enter material, design, pattern, and care instructions.', null=True),
        ),
        migrations.AddField(
            model_name='men',
            name='details',
            field=models.TextField(blank=True, help_text='Enter material, design, pattern, and care instructions.', null=True),
        ),
        migrations.AddField(
            model_name='women',
            name='details',
            field=models.TextField(blank=True, help_text='Enter material, design, pattern, and care instructions.', null=True),
        ),
    ]
