# Generated by Django 5.2.14 on 2026-05-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_accessory_details_kids_details_men_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
