# Generated by Django 5.2.14 on 2026-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_cartitem_selected_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kids',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='men',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
