# Generated by Django 5.2.14 on 2026-05-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_alter_accessory_size_alter_kids_size_alter_men_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_size',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='elected_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
